[package]
name = "experiences_plugin_media_scan"
version = "0.1.0"
edition = "2021"

[dependencies]
raqote = "0.8.4"
server_api = { path = "../../server_api/" }
timeline_types = { path = "../../timeline_types" }
serde = "1.0.197"
serde_json = "1.0.114"
